#define RAMEKA_VERSION "0.0.0.1" 
#define RAMEKA_VERSION_SHORT "NO TAG" 
#define RAMEKA_VERSION_MAJOR 0 
#define RAMEKA_VERSION_MINOR 0 
#define RAMEKA_VERSION_PATCH 0 
#define RAMEKA_VERSION_REVISION 1 
#define RAMEKA_VERSION_PRODUCT "NO TAG-RAMeka" 
